# Generated by Django 3.2.7 on 2021-09-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager_app', '0002_auto_20210921_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
