# Generated by Django 3.2.7 on 2021-09-22 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager_app', '0003_tasks_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
