# Generated by Django 3.2.7 on 2021-09-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('taskManager_app', '0009_rename_user_usertest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTest',
        ),
    ]
